### ISSUE TITLE
i'm getting a lot of warnings like this

### ISSUE THREAD

**Issue by dheeraj09** [ramkumarc/socket.io-mongodb-emitter#2]
(node) warning: possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Channel.addListener (events.js:179:15)
    at Channel.once (events.js:204:8)
    at Channel.ready (/Users/Dheeraj/Documents/Cortex-Git/ctx-api/ctx-api-mvp/dev/deploy/node_modules/socket.io-mongodb-emitter/node_modules/mubsub/lib/channel.js:247:14)

**Comment by lklepner** [comment]
@dheeraj09 has your issue been resolved? 

If I remember correctly there was a time when MongoDB reworked how listeners function and the mubsub package was updated to match shortly afterwards. Everything should be working properly at this point. If so, lets close this issue.

**Comment by lklepner** [comment]
Closing this issue as it appears to be a mubsub related issue and @dheeraj09 has not responded
